config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes

end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  embedded_in :recipe

  field :name, type: String
  field :quantity, type: String
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  embeds_many :ingredients
  embeds_many :steps

  accepts_nested_attributes_for :ingredients, :steps, allow_destroy: true, reject_if: :all_blank

end

app/models/step.rb
class Step
  include Mongoid::Document
  embedded_in :recipe

  field :title, type: String
  field :content, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :detect_variant

  def detect_variant
    request.variant = :mobile if request.user_agent.include?("Cooking Ios")
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    respond_to do |format|
      format.html
      format.html.mobile
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    respond_to do |format|
      format.html
      format.html.mobile
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, steps_attributes: [:id, :title, :content, :_destroy], ingredients_attributes: [:id, :name, :quantity, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_mobile?
    request.user_agent.include?("Cooking Ios")
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title
      = content_for?(:page_title) ? yield(:page_title) : "Cooking"
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  body class=("mobile-app" if app_mobile?)
    - unless app_mobile?
      nav.navbar.navbar-default role="navigation"
        .container-fluid
          .navbar-header
            button.navbar-toggle data-target="#navigationMenu" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            = link_to "Cooking", root_path, class: "navbar-brand"

          .collapse.navbar-collapse id="navigationMenu"
            ul.nav.navbar-nav
              li.active
                = link_to "Home", root_path

    .container-fluid
      = yield

app/views/recipes/_form.slim
= simple_form_for @recipe, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f|
  - if @recipe.errors.any?
    #error_explanation
      h2
        = pluralize(@recipe.errors.count, "error")
        | prohibited this recipe from being saved:
      ul
        - @recipe.errors.full_messages.each do |message|
          li= message

  = f.input :title
  = f.input :description, as: :text
  .col-xs-12.col-md-9.col-md-offset-3
    h3 Ingrédients :

    = f.simple_fields_for :ingredients do |ingredient|
      = render 'ingredient_fields', f: ingredient
    .links
      = link_to_add_association 'Ajouter un ingrédient', f, :ingredients

    h3 Etapes :

    = f.simple_fields_for :steps do |step|
      = render 'step_fields', f: step
    .links
      = link_to_add_association 'Ajouter une étape', f, :steps

  .actions.pull-right
    = f.submit "Enregistrer", class: "btn btn-success"

app/views/recipes/_ingredient_fields.slim
.nested-fields
  = f.input :name
  = f.input :quantity
  = link_to_remove_association "Supprimer l'ingrédient", f

app/views/recipes/_step_fields.slim
.nested-fields
  = f.input :title
  = f.input :content, as: :text
  = link_to_remove_association "Supprimer l'étape", f

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

app/views/recipes/index+mobile.slim
- @recipes.each do |recipe|
  = link_to recipe_path(recipe), class: "recipe" do
    = recipe.title
    .pull-right
      = fa_icon "chevron-right"
      
    .clearfix

app/views/recipes/index.slim
p#notice
  = notice
h1
  | Recettes
  .pull-right
    small
      = link_to 'Nouvelle recette', new_recipe_path
table.table
  thead
    tr
      th Title
      th
  tbody
    - @recipes.each do |recipe|
      tr.recipe
        td = recipe.title
        td
          .pull-right
            => link_to recipe do
              = fa_icon "eye"
            => link_to edit_recipe_path(recipe) do
              = fa_icon "edit"
            => link_to recipe, method: :delete, data: {confirm: 'Are you sure?'} do
              = fa_icon "trash"

app/views/recipes/new.slim
h1
  | Nouvelle Recette
  .pull-right
    small
      = link_to 'Revenir à la liste', recipes_path
= render 'form'

app/views/recipes/show+mobile.slim
- content_for :page_title
  | #{@recipe.title}

.recipe-step
  div
    = simple_format @recipe.description
    h3 Ingrédients
    ul
      - @recipe.ingredients.each do |ingredient|
        li
          | #{ingredient.quantity} #{ingredient.name}


  - @recipe.steps.each do |step|
    div
      div.text-center
        h2
          = step.title
      = simple_format step.content

app/views/recipes/show.slim
p#notice
  = notice

h1.page-header
  = @recipe.title
  .pull-right
    small
      = link_to 'Retour a la liste', recipes_path
= simple_format(@recipe.description)
h3 Ingrédients
ul
  - @recipe.ingredients.each do |ingredient|
    li
      | #{ingredient.quantity} #{ingredient.name}

- @recipe.steps.each do |step|
  strong= step.title
  p= simple_format step.content

div
  = link_to 'Edit', edit_recipe_path(@recipe)